"""Bake the search's best genome into a clean, dependency-free submission
main.py by literal-substituting the tunable constants in agent/main.py.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENT_SRC = os.path.join(ROOT, "agent", "main.py")

SCALAR_KEYS = [
    "TARGET_HANDS", "TILES_PER_HAND", "SPEND_RESERVE", "SURVIVAL_RESERVE_FRACTION",
    "ANIMAL_BUY_CAP_PER_TURN", "LAND_BUY_CASH_MULTIPLE", "SHED_PANIC_FRACTION",
    "WHEAT_FEED_BUFFER_MULT", "RAMP_START_DAY", "RAMP_END_DAY",
    "RISK_MULT_BEHIND", "RISK_MULT_AHEAD", "OPP_SCALE_MAX", "OPP_SCALE_MIN",
    "OPP_GROWTH_DISCOUNT_PER_TILE", "OPP_GROWTH_DISCOUNT_FLOOR",
]


def build(genome_path, out_path):
    with open(genome_path) as f:
        data = json.load(f)
    params = data["params"]

    with open(AGENT_SRC) as f:
        src = f.read()

    for key in SCALAR_KEYS:
        val = params[key]
        pattern = re.compile(rf"^{key} = .+$", re.MULTILINE)
        if not pattern.search(src):
            raise RuntimeError(f"could not find constant {key} in {AGENT_SRC}")
        src = pattern.sub(f"{key} = {val!r}", src, count=1)

    # TARGET_COUNTS is a single-line dict literal.
    tc = params["TARGET_COUNTS"]
    tc_str = "{" + ", ".join(f'"{k}": {v}' for k, v in tc.items()) + "}"
    pattern = re.compile(r"^TARGET_COUNTS = \{.*\}$", re.MULTILINE)
    if not pattern.search(src):
        raise RuntimeError("could not find TARGET_COUNTS dict in agent/main.py")
    src = pattern.sub(f"TARGET_COUNTS = {tc_str}", src, count=1)

    # RESERVE_PRICE is a dict literal spanning multiple lines; replace it whole.
    rp = params["RESERVE_PRICE"]
    rp_str = "{\n" + "\n".join(f'    "{k}": {v:.2f},' for k, v in rp.items()) + "\n}"
    pattern = re.compile(r"^RESERVE_PRICE = \{.*?\n\}", re.MULTILINE | re.DOTALL)
    if not pattern.search(src):
        raise RuntimeError("could not find RESERVE_PRICE dict in agent/main.py")
    src = pattern.sub(f"RESERVE_PRICE = {rp_str}", src, count=1)

    header = (
        f'"""Baked from search checkpoint (generation {data.get("generation")}, '
        f'fitness {data.get("fitness"):.1f}, win_rate {data.get("win_rate"):.2f}).\n'
        f'Generated by search/build_submission.py -- do not hand-edit constants here,\n'
        f'edit agent/main.py and re-run the search / this script instead.\n"""\n'
    )
    src = header + src

    with open(out_path, "w") as f:
        f.write(src)
    print(f"wrote {out_path}")
    print(f"  generation={data.get('generation')} fitness={data.get('fitness'):.1f} "
          f"win_rate={data.get('win_rate'):.2f}")


if __name__ == "__main__":
    genome_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "search", "checkpoints", "best_genome.json")
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "submission", "main.py")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    build(genome_path, out_path)
