"""Fit dynamic/opp_predict.THETA, and report it against the current estimator.

Training data is generated by playing games and recording, at sampled days, the
public feature vector alongside the opponent's ACTUAL remaining sales to the end
of that game -- ground truth from the simulator's own commit hook, so the target
is exact rather than inferred.

Held-out evaluation is by GAME, not by row. Rows from one game share its board,
its shop draw and its opponent, so a random row split would let the model see
the answer to the game it is being tested on and would report a fit that does
not exist. The reported numbers are directly comparable to the structural
forecast's in `dynamic/opp_state_test.py`.

Kept deliberately light on CPU: it is meant to run alongside the GA, which owns
the 26 physical cores.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or ".") != _HERE]
sys.path.insert(0, ROOT)

from dynamic import opp_predict as OP                 # noqa: E402
from dynamic.opp_state import OppState                # noqa: E402
from planner.simulate import Simulator, _agent_caller  # noqa: E402
from route.opponent import OpponentModel              # noqa: E402

ITEMS = ["STRAWBERRY", "MELON", "MILK", "WOOL", "EGG", "WHEAT", "FERTILIZER"]
OUT = os.path.join(ROOT, "dynamic", "opp_theta.json")
POOL = ["kaggriculture-multi-route-farming-agent",
        "v111-8c4s-economic-core-premium-lead",
        "kaggriculture-frontier-the-soil-remembers-rain",
        "kaggriculture-3000-socre",
        "kaggriculture-rank-your-agent",
        "strong-barnyard-economist"]
_n = [0]


def _load(path, genome=None):
    import importlib.util
    _n[0] += 1
    spec = importlib.util.spec_from_file_location(f"pf_{_n[0]}", path)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    if genome is not None:
        m.configure(genome)
        return m.agent
    return getattr(m, "_submission_entry", None) or m.agent


def collect(seed, us_path, opp_name, sample_every=2, genome=None):
    """One game -> [(item, x, y)], y = their actual remaining sales."""
    me = _load(us_path, genome)
    op = _load(os.path.join(ROOT, "opponents", f"{opp_name}.py"))
    sim = Simulator.new_episode(configuration={"episodeSteps": 720}, seed=seed)
    truth = {}

    def on_commit(pid, opn, item, price):
        if pid == 1 and opn == "SELL":
            truth[item] = truth.get(item, 0) + 1
    sim.on_commit = on_commit

    st, om = OppState(), OpponentModel()
    c0, c1 = _agent_caller(me), _agent_caller(op)
    my_prev = {}
    samples = []
    while sim.step < 719:
        o = sim.observation_for(0)
        shops = tuple(o["town"].get("unlocked_shops", []))
        om.observe(dict(sim.market["inventory"]), sim.step, shops, my_prev)
        if om.recent and om.recent[-1][0] == sim.step:
            st.record_sales(om.recent[-1][1])
        opp_farm = o["farms"][1]
        st.observe(opp_farm, o["day"], o["hour"])
        st.reconcile(o["market"].get("prices") or {},
                     len(opp_farm.get("hands") or []))
        if sim.step % 24 == 12 and o["day"] % sample_every == 0 and o["day"] >= 4:
            for item in ITEMS:
                samples.append((item,
                                OP.feature_row(item, opp_farm, o["day"], st),
                                truth.get(item, 0)))
        a = c0(o, sim.cfg)
        b = c1(sim.observation_for(1), sim.cfg)
        my_prev = {}
        if isinstance(a, dict):
            for act in a.get("market", []) or []:
                if act and act[0] == "SELL":
                    my_prev[act[1]] = my_prev.get(act[1], 0) + int(act[2])
        sim.step_actions(a, b)
    final = dict(truth)
    # y is what is STILL to come at the sample point, not the running total
    return [(item, x, max(0, final.get(item, 0) - sold_so_far))
            for (item, x, sold_so_far) in samples]


def main():
    n_seeds = int(sys.argv[1]) if len(sys.argv) > 1 else 6
    ridge = float(sys.argv[2]) if len(sys.argv) > 2 else 1.0
    # WHOSE GAMES THE MODEL IS FIT ON MATTERS, and the first version got this
    # wrong. It trained on games where the TAPE held our seat, then the model
    # was deployed in games where agent2/3 holds it. The opponent's remaining
    # sales depend on the board we create -- our tile count shifts the weed RNG
    # and therefore the shop draw, and our own selling sets the book they sell
    # into -- so that is covariate shift, the same failure that made behavioural
    # cloning bank $288 in section 21. Train on our own games.
    us_arg = sys.argv[3] if len(sys.argv) > 3 else "self"
    if us_arg == "tape":
        us = os.path.join(ROOT, "opponents", f"{POOL[0]}.py")
        genome = None
    else:
        us = os.path.join(ROOT, "dynamic", "agent2.py")
        from route.search import to_params
        genome = to_params(dict(json.load(open(os.path.join(
            ROOT, "dynamic", "best_genome.json")))["genome"]))
        genome["OPP_MODEL"] = 1
    print(f"training on games where WE are: {os.path.basename(us)}"
          f"{' (configured)' if genome else ''}", flush=True)

    import random
    rng = random.Random(24680)
    seeds = [rng.randrange(10 ** 6, 2 ** 31 - 1) for _ in range(n_seeds)]
    games = []
    for i, seed in enumerate(seeds):
        for opp in POOL:
            games.append(collect(seed, us, opp, genome=genome))
        print(f"  seed {i + 1}/{n_seeds} done ({sum(len(g) for g in games):,} rows)",
              flush=True)

    # split by GAME, never by row
    cut = int(len(games) * 0.75)
    train_games, test_games = games[:cut], games[cut:]
    theta, report = {}, {}
    print(f"\n{'item':<12}{'model bias':>12}{'|err|':>9}{'corr':>7}   "
          f"{'structural bias':>17}{'|err|':>9}{'corr':>7}")
    for item in ITEMS:
        tr = [(x, y) for g in train_games for (it, x, y) in g if it == item]
        te = [(x, y) for g in test_games for (it, x, y) in g if it == item]
        th = OP.fit(tr, ridge=ridge)
        b1, e1, c1_ = OP.score(th, te)
        b0, e0, c0_ = OP.score(None, te)      # None == structural forecast
        theta[item] = th
        report[item] = {"model": [b1, e1, c1_], "structural": [b0, e0, c0_],
                        "n_train": len(tr), "n_test": len(te)}
        print(f"{item:<12}{b1:>12.1f}{e1:>9.1f}{c1_:>7.2f}   "
              f"{b0:>17.1f}{e0:>9.1f}{c0_:>7.2f}")
    json.dump({"theta": theta, "features": list(OP.FEATURES),
               "report": report, "ridge": ridge,
               "n_games": len(games), "n_test_games": len(test_games)},
              open(OUT, "w"), indent=1)
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
