"""Build the bottom of the curriculum by handicapping a strong agent.

Grading every agent on disk found 117 usable builds and exactly TWO in the band
we win 20-80% of; the rest sit at 0%. That is not a pool that is merely too
strong, it is a ladder with no bottom rungs -- almost everything in the repo is
a tape derivative, and the tape is far above the dynamic scheduler. A curriculum
cannot be found here, it has to be constructed.

The dial is action dropout. A wrapped agent forwards the real agent's decision
with probability 1-eps and substitutes PASS otherwise, independently per unit
per turn. That is smooth, monotone in eps, and preserves the SHAPE of good play
at every rung -- the learner still faces sensible farming, just less of it,
rather than a differently-broken strategy. Market orders are dropped on the same
coin so a handicapped opponent does not out-trade its own production.

eps = 0.0 is the source agent exactly, which doubles as the identity control.

    python dynamic/rl/handicap.py            # generate + grade the rungs
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or ".") != _HERE]
sys.path.insert(0, ROOT)

OUTDIR = os.path.join(ROOT, "opponents", "rungs")

TEMPLATE = '''"""Handicapped rung for the RL curriculum: {src} at eps={eps}.

Generated by dynamic/rl/handicap.py. Forwards the source agent's decision with
probability {keep}, substituting PASS otherwise, independently per unit per
turn. Smooth and monotone in eps, and it keeps the SHAPE of competent play at
every rung instead of substituting a differently-broken strategy.
"""
import os
import random
import sys

_ROOT = {root!r}
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

import importlib.util as _iu

_spec = _iu.spec_from_file_location("_rung_src_{tag}", {src_path!r})
_m = _iu.module_from_spec(_spec)
_spec.loader.exec_module(_m)
{configure}
_inner = getattr(_m, "_submission_entry", None) or _m.agent
_EPS = {eps}
_rng = random.Random({seed})


def agent(obs, config=None):
    a = _inner(obs) if _inner.__code__.co_argcount < 2 else _inner(obs, config)
    if not isinstance(a, dict):
        return a
    out = dict(a)
    if _rng.random() < _EPS:
        out["farmer"] = ["PASS"]
    hands = out.get("hands") or []
    out["hands"] = [["PASS"] if _rng.random() < _EPS else h for h in hands]
    # Drop orders on the same coin, so a handicapped farm cannot out-trade the
    # production it is no longer doing.
    out["market"] = [o for o in (out.get("market") or [])
                     if _rng.random() >= _EPS]
    return out
'''

CONFIGURE = '''
import json as _json
from route.search import to_params as _tp
_g = _json.load(open(os.path.join(_ROOT, "dynamic", "best_genome3.json")))["genome"]
_p = _tp(dict(_g))
_p["OPP_MODEL"] = 1
_p["SHED_PANIC_FRACTION"] = 0.40
_m.configure(_p)
'''


# THE LADDER NEEDS TWO TIERS, and the first version only had one. Handicapping
# agent4 tops out AT agent4, which is where the policy already starts -- clearing
# rung 6 means drawing level with your own baseline, not beating anything. The
# distance that matters is the 80,210 from there to the shipped tape+market
# build, and nothing in tier 1 covers it.
#
# Tier 2 handicaps the STRONG builds by the same dial, so the ladder continues
# smoothly from "a badly crippled tape" up to the full-strength article. eps=0.0
# is the real agent, so the top rung IS our best model: clearing the ladder and
# beating everything we have become the same statement.
TIER1 = (0.75, 0.6, 0.45, 0.3, 0.2, 0.12, 0.06)
TIER2 = (0.55, 0.4, 0.28, 0.18, 0.10, 0.04, 0.0)


def generate(eps_values=TIER1, tier2=TIER2):
    os.makedirs(OUTDIR, exist_ok=True)
    made = []
    # tier 1: our own scheduler, weakened -- the bottom of the ladder
    src_path = os.path.join(ROOT, "dynamic", "agent4.py")
    for i, eps in enumerate(eps_values):
        tag = f"t1_eps{int(eps * 100):03d}"
        dest = os.path.join(OUTDIR, f"rung_{i:02d}_{tag}.py")
        open(dest, "w").write(TEMPLATE.format(
            src="agent4", eps=eps, keep=round(1 - eps, 2), tag=tag,
            root=ROOT, src_path=src_path, seed=1000 + i,
            configure=CONFIGURE))
        made.append(dest)
    # tier 2: the strongest build we have, weakened then restored to full
    strong = os.path.join(ROOT, "submission", "main.py")
    if not os.path.exists(strong):
        strong = os.path.join(ROOT, "opponents",
                              "kaggriculture-multi-route-farming-agent.py")
    for j, eps in enumerate(tier2):
        i = len(eps_values) + j
        tag = f"t2_eps{int(eps * 100):03d}"
        dest = os.path.join(OUTDIR, f"rung_{i:02d}_{tag}.py")
        open(dest, "w").write(TEMPLATE.format(
            src=os.path.basename(strong), eps=eps, keep=round(1 - eps, 2),
            tag=tag, root=ROOT, src_path=strong, seed=2000 + j,
            configure=""))
        made.append(dest)
    return made


def main():
    made = generate()
    print(f"generated {len(made)} rungs in {OUTDIR}")
    for m in made:
        print("  " + os.path.relpath(m, ROOT))
    print()
    print("grade them with:")
    print("  python dynamic/rl/grade_pool.py 4 10 400")


if __name__ == "__main__":
    main()
