"""Bolt the SHIPPED market-intervention overlay onto our own scheduler.

The shipped build is tape + market layer, and every experiment in this project
has only ever touched the farming half. The overlay is a pure wrapper --
`_IV_BASE_AGENT(obs)` runs first and the overlay only edits MARKET ORDERS, never
a tile -- so it is base-agnostic and has simply never been pointed at the
scheduler.

It is worth +1,611 paired against plain kawa (HANDOFF section 6), built on the
exact opponent-sales inference, and it is additive by construction: the shape
that is the only one to have produced a confirmed gain here.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or ".") != _HERE]
sys.path.insert(0, ROOT)

from pbt.intervene import PREMIUM, PREMIUM_FERT, intervene_src  # noqa: E402

HEAD = '''"""Our scheduler with the shipped market-intervention overlay.

Generated by dynamic/tree/bake_overlay.py -- do not edit by hand.
"""
import json
import os
import sys

_ROOT = {root!r}
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

import importlib.util as _iu

_spec = _iu.spec_from_file_location("_ov_base", {base!r})
_m = _iu.module_from_spec(_spec)
_spec.loader.exec_module(_m)

from route.search import to_params as _tp
_g = _tp(dict(json.load(open(os.path.join(_ROOT, "dynamic", "best_genome3.json")))["genome"]))
_g["OPP_MODEL"] = 1
_g["SHED_PANIC_FRACTION"] = 0.40
{extra}
_m.configure(_g)


def agent(obs):
    """The base agent under a module-level name.

    The overlay template ends with `_IV_BASE_AGENT = agent` and then redefines
    `agent` itself, mirroring how route/bake.py appends it after the tape source
    -- so the base has to be reachable as a module-level `agent` here, not just
    assigned into _IV_BASE_AGENT (which the template would overwrite).
    """
    return _m.agent(obs)
'''


def build(dest, base=None, **kw):
    base = base or os.path.join(ROOT, "dynamic", "agent4.py")
    extra = "\n".join(f"_g[{k!r}] = {v!r}" for k, v in
                      (kw.pop("genome_overrides", {}) or {}).items())
    items = PREMIUM_FERT if kw.pop("fert", 1) else PREMIUM
    src = HEAD.format(root=ROOT, base=base, extra=extra)
    src += intervene_src(enabled=1, items=items, **kw)
    src += "\n\ndef _submission_entry(obs):\n    return agent(obs)\n"
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, "w").write(src)
    return dest


if __name__ == "__main__":
    out = os.path.join(ROOT, "agents", "sched_overlay.py")
    # the shipped configuration, verbatim from HANDOFF section 0
    build(out, dump_frac=0.7, lead=3, struct=1, min_price=0.20)
    print("wrote", out)
