"""Handicapped rung for the RL curriculum: agent4 at eps=0.2.

Generated by dynamic/rl/handicap.py. Forwards the source agent's decision with
probability 0.8, substituting PASS otherwise, independently per unit per
turn. Smooth and monotone in eps, and it keeps the SHAPE of competent play at
every rung instead of substituting a differently-broken strategy.
"""
import os
import random
import sys

_ROOT = '/home/yilewang/kaggriculture'
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

import importlib.util as _iu

_spec = _iu.spec_from_file_location("_rung_src_t1_eps020", '/home/yilewang/kaggriculture/dynamic/agent4.py')
_m = _iu.module_from_spec(_spec)
_spec.loader.exec_module(_m)

import json as _json
from route.search import to_params as _tp
_g = _json.load(open(os.path.join(_ROOT, "dynamic", "best_genome3.json")))["genome"]
_p = _tp(dict(_g))
_p["OPP_MODEL"] = 1
_p["SHED_PANIC_FRACTION"] = 0.40
_m.configure(_p)

_inner = getattr(_m, "_submission_entry", None) or _m.agent
_EPS = 0.2
_rng = random.Random(1004)


def agent(obs, config=None):
    a = _inner(obs) if _inner.__code__.co_argcount < 2 else _inner(obs, config)
    if not isinstance(a, dict):
        return a
    out = dict(a)
    if _rng.random() < _EPS:
        out["farmer"] = ["PASS"]
    hands = out.get("hands") or []
    out["hands"] = [["PASS"] if _rng.random() < _EPS else h for h in hands]
    # Drop orders on the same coin, so a handicapped farm cannot out-trade the
    # production it is no longer doing.
    out["market"] = [o for o in (out.get("market") or [])
                     if _rng.random() >= _EPS]
    return out
